#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

#define ITEM_NONE 0

// Poké Balls
#define ITEM_POKE_BALL 1
#define ITEM_GREAT_BALL 2
#define ITEM_ULTRA_BALL 3
#define ITEM_MASTER_BALL 4
#define ITEM_PREMIER_BALL 5
#define ITEM_HEAL_BALL 6
#define ITEM_NET_BALL 7
#define ITEM_NEST_BALL 8
#define ITEM_DIVE_BALL 9
#define ITEM_DUSK_BALL 10
#define ITEM_TIMER_BALL 11
#define ITEM_QUICK_BALL 12
#define ITEM_REPEAT_BALL 13
#define ITEM_LUXURY_BALL 14
#define ITEM_LEVEL_BALL 15
#define ITEM_LURE_BALL 16
#define ITEM_MOON_BALL 17
#define ITEM_FRIEND_BALL 18
#define ITEM_LOVE_BALL 19
#define ITEM_FAST_BALL 20
#define ITEM_HEAVY_BALL 21
#define ITEM_DREAM_BALL 22
#define ITEM_SAFARI_BALL 23
#define ITEM_SPORT_BALL 24
#define ITEM_PARK_BALL 25
#define ITEM_BEAST_BALL 26
#define ITEM_CHERISH_BALL 27

// Medicine
#define ITEM_POTION 28
#define ITEM_SUPER_POTION 29
#define ITEM_HYPER_POTION 30
#define ITEM_MAX_POTION 31
#define ITEM_FULL_RESTORE 32
#define ITEM_REVIVE 33
#define ITEM_MAX_REVIVE 34
#define ITEM_FRESH_WATER 35
#define ITEM_SODA_POP 36
#define ITEM_LEMONADE 37
#define ITEM_MOOMOO_MILK 38
#define ITEM_ENERGY_POWDER 39
#define ITEM_ENERGYPOWDER ITEM_ENERGY_POWDER // Pre-Gen VI name
#define ITEM_ENERGY_ROOT 40
#define ITEM_HEAL_POWDER 41
#define ITEM_REVIVAL_HERB 42
#define ITEM_ANTIDOTE 43
#define ITEM_PARALYZE_HEAL 44
#define ITEM_PARLYZ_HEAL ITEM_PARALYZE_HEAL // Pre-Gen VI name
#define ITEM_BURN_HEAL 45
#define ITEM_ICE_HEAL 46
#define ITEM_AWAKENING 47
#define ITEM_FULL_HEAL 48
#define ITEM_ETHER 49
#define ITEM_MAX_ETHER 50
#define ITEM_ELIXIR 51
#define ITEM_ELIXER ITEM_ELIXIR // Pre-Gen III name
#define ITEM_MAX_ELIXIR 52
#define ITEM_MAX_ELIXER ITEM_MAX_ELIXIR // Pre-Gen III name
#define ITEM_BERRY_JUICE 53
#define ITEM_SACRED_ASH 54
#define ITEM_SWEET_HEART 55
#define ITEM_MAX_HONEY 56

// Regional Specialties
#define ITEM_PEWTER_CRUNCHIES 57
#define ITEM_RAGE_CANDY_BAR 58
#define ITEM_RAGECANDYBAR ITEM_RAGE_CANDY_BAR // Pre-Gen VI name
#define ITEM_LAVA_COOKIE 59
#define ITEM_OLD_GATEAU 60
#define ITEM_CASTELIACONE 61
#define ITEM_LUMIOSE_GALETTE 62
#define ITEM_SHALOUR_SABLE 63
#define ITEM_BIG_MALASADA 64

// Vitamins
#define ITEM_HP_UP 65
#define ITEM_PROTEIN 66
#define ITEM_IRON 67
#define ITEM_CALCIUM 68
#define ITEM_ZINC 69
#define ITEM_CARBOS 70
#define ITEM_B12 71
#define ITEM_OMEGA3 72
#define ITEM_PP_UP 73
#define ITEM_PP_MAX 74

// EV Feathers
#define ITEM_HEALTH_FEATHER 75
#define ITEM_HEALTH_WING ITEM_HEALTH_FEATHER // Pre-Gen VIII name
#define ITEM_MUSCLE_FEATHER 76
#define ITEM_MUSCLE_WING ITEM_MUSCLE_FEATHER // Pre-Gen VIII name
#define ITEM_RESIST_FEATHER 77
#define ITEM_RESIST_WING ITEM_RESIST_FEATHER // Pre-Gen VIII name
#define ITEM_GENIUS_FEATHER 78
#define ITEM_GENIUS_WING ITEM_GENIUS_FEATHER // Pre-Gen VIII name
#define ITEM_CLEVER_FEATHER 79
#define ITEM_CLEVER_WING ITEM_CLEVER_FEATHER // Pre-Gen VIII name
#define ITEM_SWIFT_FEATHER 80
#define ITEM_SWIFT_WING ITEM_SWIFT_FEATHER // Pre-Gen VIII name
#define ITEM_ALERT_FEATHER 81
#define ITEM_ALERT_WING ITEM_ALERT_FEATHER // Pre-Gen VIII name
#define ITEM_KEEN_FEATHER 82
#define ITEM_KEEN_WING ITEM_KEEN_FEATHER // Pre-Gen VIII name

// Ability Modifiers
#define ITEM_ABILITY_CAPSULE 83
#define ITEM_ABILITY_PATCH 84

// Mints
#define ITEM_LONELY_MINT 85
#define ITEM_ADAMANT_MINT 86
#define ITEM_NAUGHTY_MINT 87
#define ITEM_BRAVE_MINT 88
#define ITEM_AUSTERE_MINT 89
#define ITEM_WILD_MINT 90
#define ITEM_BOLD_MINT 91
#define ITEM_IMPISH_MINT 92
#define ITEM_LAX_MINT 93
#define ITEM_RELAXED_MINT 94
#define ITEM_WARY_MINT 95
#define ITEM_STRICT_MINT 96
#define ITEM_MODEST_MINT 97
#define ITEM_MILD_MINT 98
#define ITEM_RASH_MINT 99
#define ITEM_QUIET_MINT 100
#define ITEM_POLITE_MINT 101
#define ITEM_SPACEY_MINT 102
#define ITEM_CALM_MINT 103
#define ITEM_GENTLE_MINT 104
#define ITEM_CAREFUL_MINT 105
#define ITEM_SASSY_MINT 106
#define ITEM_WISE_MINT 107
#define ITEM_JEALOUS_MINT 108
#define ITEM_TIMID_MINT 109
#define ITEM_HASTY_MINT 110
#define ITEM_JOLLY_MINT 111
#define ITEM_NAIVE_MINT 112
#define ITEM_PROUD_MINT 113
#define ITEM_VALIANT_MINT 114
#define ITEM_SERIOUS_MINT 115
#define ITEM_SHY_MINT 116
#define ITEM_CURIOUS_MINT 117
#define ITEM_ALERT_MINT 118
#define ITEM_SILLY_MINT 119
#define ITEM_ANXIOUS_MINT 120
#define ITEM_ERRATIC_MINT 121
#define ITEM_SUAVE_MINT 122
#define ITEM_PASSIVE_MINT 123
#define ITEM_SKEPTIC_MINT 124
#define ITEM_DEVOTED_MINT 125
#define ITEM_PATIENT_MINT 126
#define ITEM_FOCUSED_MINT 127

// Candy
#define ITEM_RARE_CANDY 128
#define ITEM_EXP_CANDY_XS 129
#define ITEM_EXP_CANDY_S 130
#define ITEM_EXP_CANDY_M 131
#define ITEM_EXP_CANDY_L 132
#define ITEM_EXP_CANDY_XL 133
#define ITEM_DYNAMAX_CANDY 134

// Medicinal Flutes
#define ITEM_BLUE_FLUTE 135
#define ITEM_YELLOW_FLUTE 136
#define ITEM_RED_FLUTE 137

// Encounter-modifying Flutes
#define ITEM_BLACK_FLUTE 138
#define ITEM_WHITE_FLUTE 139

// Encounter Modifiers
#define ITEM_REPEL 140
#define ITEM_SUPER_REPEL 141
#define ITEM_MAX_REPEL 142
#define ITEM_LURE 143
#define ITEM_SUPER_LURE 144
#define ITEM_MAX_LURE 145

#define ITEM_ESCAPE_ROPE 146

// X Items
#define ITEM_X_ATTACK 147
#define ITEM_X_DEFENSE 148
#define ITEM_X_DEFEND ITEM_X_DEFENSE // Pre-Gen VI name
#define ITEM_X_SP_ATK 149
#define ITEM_X_SPECIAL ITEM_X_SP_ATK // Pre-Gen VI name
#define ITEM_X_SP_DEF 150
#define ITEM_X_SPEED 151
#define ITEM_X_AWARE 152

#define ITEM_DIRE_HIT 153
#define ITEM_GUARD_SPEC 154

// Escape Items
#define ITEM_POKE_DOLL 155
#define ITEM_FLUFFY_TAIL 156
#define ITEM_POKE_TOY 157

#define ITEM_MAX_MUSHROOMS 158

// Treasures
#define ITEM_BOTTLE_CAP 159
#define ITEM_GOLD_BOTTLE_CAP 160
#define ITEM_NUGGET 161
#define ITEM_BIG_NUGGET 162
#define ITEM_TINY_MUSHROOM 163
#define ITEM_TINYMUSHROOM ITEM_TINY_MUSHROOM // Pre-Gen VI name
#define ITEM_BIG_MUSHROOM 164
#define ITEM_BALM_MUSHROOM 165
#define ITEM_BALMMUSHROOM ITEM_BALM_MUSHROOM // Pre-Gen VI name
#define ITEM_PEARL 166
#define ITEM_BIG_PEARL 167
#define ITEM_PEARL_STRING 168
#define ITEM_STARDUST 169
#define ITEM_STAR_PIECE 170
#define ITEM_COMET_SHARD 171
#define ITEM_SHOAL_SALT 172
#define ITEM_SHOAL_SHELL 173
#define ITEM_RED_SHARD 174
#define ITEM_BLUE_SHARD 175
#define ITEM_YELLOW_SHARD 176
#define ITEM_GREEN_SHARD 177
#define ITEM_HEART_SCALE 178
#define ITEM_HONEY 179
#define ITEM_RARE_BONE 180
#define ITEM_ODD_KEYSTONE 181
#define ITEM_PRETTY_FEATHER 182
#define ITEM_PRETTY_WING ITEM_PRETTY_FEATHER // Pre-Gen VIII name
#define ITEM_RELIC_COPPER 183
#define ITEM_RELIC_SILVER 184
#define ITEM_RELIC_GOLD 185
#define ITEM_RELIC_VASE 186
#define ITEM_RELIC_BAND 187
#define ITEM_RELIC_STATUE 188
#define ITEM_RELIC_CROWN 189
#define ITEM_STRANGE_SOUVENIR 190

// Fossils
#define ITEM_HELIX_FOSSIL 191
#define ITEM_DOME_FOSSIL 192
#define ITEM_OLD_AMBER 193
#define ITEM_ROOT_FOSSIL 194
#define ITEM_CLAW_FOSSIL 195
#define ITEM_ARMOR_FOSSIL 196
#define ITEM_SKULL_FOSSIL 197
#define ITEM_COVER_FOSSIL 198
#define ITEM_PLUME_FOSSIL 199
#define ITEM_JAW_FOSSIL 200
#define ITEM_SAIL_FOSSIL 201
#define ITEM_FOSSILIZED_BIRD 202
#define ITEM_FOSSILIZED_FISH 203
#define ITEM_FOSSILIZED_DRAKE 204
#define ITEM_FOSSILIZED_DINO 205

// Mulch
#define ITEM_GROWTH_MULCH 206
#define ITEM_DAMP_MULCH 207
#define ITEM_STABLE_MULCH 208
#define ITEM_GOOEY_MULCH 209
#define ITEM_RICH_MULCH 210
#define ITEM_SURPRISE_MULCH 211
#define ITEM_BOOST_MULCH 212
#define ITEM_AMAZE_MULCH 213

// Apricorns
#define ITEM_RED_APRICORN 214
#define ITEM_BLUE_APRICORN 215
#define ITEM_BLU_APRICORN ITEM_BLUE_APRICORN // Pre-Gen VI name
#define ITEM_YELLOW_APRICORN 216
#define ITEM_YLW_APRICORN ITEM_YELLOW_APRICORN // Pre-Gen VI name
#define ITEM_GREEN_APRICORN 217
#define ITEM_GRN_APRICORN ITEM_GREEN_APRICORN // Pre-Gen VI name
#define ITEM_PINK_APRICORN 218
#define ITEM_PNK_APRICORN ITEM_PINK_APRICORN // Pre-Gen VI name
#define ITEM_WHITE_APRICORN 219
#define ITEM_WHT_APRICORN ITEM_WHITE_APRICORN // Pre-Gen VI name
#define ITEM_BLACK_APRICORN 220
#define ITEM_BLK_APRICORN ITEM_BLACK_APRICORN // Pre-Gen VI name

#define ITEM_WISHING_PIECE 221
#define ITEM_GALARICA_TWIG 222
#define ITEM_ARMORITE_ORE 223
#define ITEM_DYNITE_ORE 224

// Mail
#define ITEM_ORANGE_MAIL 225
#define ITEM_HARBOR_MAIL 226
#define ITEM_GLITTER_MAIL 227
#define ITEM_MECH_MAIL 228
#define ITEM_WOOD_MAIL 229
#define ITEM_WAVE_MAIL 230
#define ITEM_BEAD_MAIL 231
#define ITEM_SHADOW_MAIL 232
#define ITEM_TROPIC_MAIL 233
#define ITEM_DREAM_MAIL 234
#define ITEM_FAB_MAIL 235
#define ITEM_RETRO_MAIL 236

#define FIRST_MAIL_INDEX ITEM_ORANGE_MAIL

// Evolution Items
#define ITEM_FIRE_STONE 237
#define ITEM_WATER_STONE 238
#define ITEM_THUNDER_STONE 239
#define ITEM_THUNDERSTONE ITEM_THUNDER_STONE // Pre-Gen VI name
#define ITEM_LEAF_STONE 240
#define ITEM_ICE_STONE 241
#define ITEM_SUN_STONE 242
#define ITEM_MOON_STONE 243
#define ITEM_SHINY_STONE 244
#define ITEM_DUSK_STONE 245
#define ITEM_DAWN_STONE 246
#define ITEM_SWEET_APPLE 247
#define ITEM_TART_APPLE 248
#define ITEM_CRACKED_POT 249
#define ITEM_CHIPPED_POT 250
#define ITEM_GALARICA_CUFF 251
#define ITEM_GALARICA_WREATH 252
#define ITEM_DRAGON_SCALE 253
#define ITEM_UPGRADE 254
#define ITEM_UP_GRADE ITEM_UPGRADE // Pre-Gen VIII name
#define ITEM_PROTECTOR 255
#define ITEM_ELECTIRIZER 256
#define ITEM_MAGMARIZER 257
#define ITEM_DUBIOUS_DISC 258
#define ITEM_REAPER_CLOTH 259
#define ITEM_PRISM_SCALE 260
#define ITEM_WHIPPED_DREAM 261
#define ITEM_SACHET 262
#define ITEM_OVAL_STONE 263
#define ITEM_STRAWBERRY_SWEET 264
#define ITEM_LOVE_SWEET 265
#define ITEM_BERRY_SWEET 266
#define ITEM_CLOVER_SWEET 267
#define ITEM_FLOWER_SWEET 268
#define ITEM_STAR_SWEET 269
#define ITEM_RIBBON_SWEET 270

#define ITEM_EVERSTONE 271

// Nectars
#define ITEM_RED_NECTAR 272
#define ITEM_YELLOW_NECTAR 273
#define ITEM_PINK_NECTAR 274
#define ITEM_PURPLE_NECTAR 275

// Plates
#define ITEM_FLAME_PLATE 276
#define ITEM_SPLASH_PLATE 277
#define ITEM_ZAP_PLATE 278
#define ITEM_MEADOW_PLATE 279
#define ITEM_ICICLE_PLATE 280
#define ITEM_FIST_PLATE 281
#define ITEM_TOXIC_PLATE 282
#define ITEM_EARTH_PLATE 283
#define ITEM_SKY_PLATE 284
#define ITEM_MIND_PLATE 285
#define ITEM_INSECT_PLATE 286
#define ITEM_STONE_PLATE 287
#define ITEM_SPOOKY_PLATE 288
#define ITEM_DRACO_PLATE 289
#define ITEM_DREAD_PLATE 290
#define ITEM_IRON_PLATE 291
#define ITEM_PIXIE_PLATE 292

// Drives
#define ITEM_DOUSE_DRIVE 293
#define ITEM_SHOCK_DRIVE 294
#define ITEM_BURN_DRIVE 295
#define ITEM_CHILL_DRIVE 296

// Memories
#define ITEM_FIRE_MEMORY 297
#define ITEM_WATER_MEMORY 298
#define ITEM_ELECTRIC_MEMORY 299
#define ITEM_GRASS_MEMORY 300
#define ITEM_ICE_MEMORY 301
#define ITEM_FIGHTING_MEMORY 302
#define ITEM_POISON_MEMORY 303
#define ITEM_GROUND_MEMORY 304
#define ITEM_FLYING_MEMORY 305
#define ITEM_PSYCHIC_MEMORY 306
#define ITEM_BUG_MEMORY 307
#define ITEM_ROCK_MEMORY 308
#define ITEM_GHOST_MEMORY 309
#define ITEM_DRAGON_MEMORY 310
#define ITEM_DARK_MEMORY 311
#define ITEM_STEEL_MEMORY 312
#define ITEM_FAIRY_MEMORY 313

#define ITEM_RUSTED_SWORD 314
#define ITEM_RUSTED_SHIELD 315

// Colored Orbs
#define ITEM_RED_ORB 316
#define ITEM_BLUE_ORB 317

// Mega Stones
#define ITEM_VENUSAURITE 318
#define ITEM_CHARIZARDITE_X 319
#define ITEM_CHARIZARDITE_Y 320
#define ITEM_BLASTOISINITE 321
#define ITEM_BEEDRILLITE 322
#define ITEM_PIDGEOTITE 323
#define ITEM_ALAKAZITE 324
#define ITEM_SLOWBRONITE 325
#define ITEM_GENGARITE 326
#define ITEM_KANGASKHANITE 327
#define ITEM_PINSIRITE 328
#define ITEM_GYARADOSITE 329
#define ITEM_AERODACTYLITE 330
#define ITEM_MEWTWONITE_X 331
#define ITEM_MEWTWONITE_Y 332
#define ITEM_AMPHAROSITE 333
#define ITEM_STEELIXITE 334
#define ITEM_SCIZORITE 335
#define ITEM_HERACRONITE 336
#define ITEM_HOUNDOOMINITE 337
#define ITEM_TYRANITARITE 338
#define ITEM_SCEPTILITE 339
#define ITEM_BLAZIKENITE 340
#define ITEM_SWAMPERTITE 341
#define ITEM_GARDEVOIRITE 342
#define ITEM_SABLENITE 343
#define ITEM_MAWILITE 344
#define ITEM_AGGRONITE 345
#define ITEM_MEDICHAMITE 346
#define ITEM_MANECTITE 347
#define ITEM_SHARPEDONITE 348
#define ITEM_CAMERUPTITE 349
#define ITEM_ALTARIANITE 350
#define ITEM_BANETTITE 351
#define ITEM_ABSOLITE 352
#define ITEM_GLALITITE 353
#define ITEM_SALAMENCITE 354
#define ITEM_METAGROSSITE 355
#define ITEM_LATIASITE 356
#define ITEM_LATIOSITE 357
#define ITEM_LOPUNNITE 358
#define ITEM_GARCHOMPITE 359
#define ITEM_LUCARIONITE 360
#define ITEM_ABOMASITE 361
#define ITEM_GALLADITE 362
#define ITEM_AUDINITE 363
#define ITEM_DIANCITE 364

// Gems
#define ITEM_NORMAL_GEM 365
#define ITEM_FIRE_GEM 366
#define ITEM_WATER_GEM 367
#define ITEM_ELECTRIC_GEM 368
#define ITEM_GRASS_GEM 369
#define ITEM_ICE_GEM 370
#define ITEM_FIGHTING_GEM 371
#define ITEM_POISON_GEM 372
#define ITEM_GROUND_GEM 373
#define ITEM_FLYING_GEM 374
#define ITEM_PSYCHIC_GEM 375
#define ITEM_BUG_GEM 376
#define ITEM_ROCK_GEM 377
#define ITEM_GHOST_GEM 378
#define ITEM_DRAGON_GEM 379
#define ITEM_DARK_GEM 380
#define ITEM_STEEL_GEM 381
#define ITEM_FAIRY_GEM 382

// Z-Crystals
#define ITEM_NORMALIUM_Z 383
#define ITEM_FIRIUM_Z 384
#define ITEM_WATERIUM_Z 385
#define ITEM_ELECTRIUM_Z 386
#define ITEM_GRASSIUM_Z 387
#define ITEM_ICIUM_Z 388
#define ITEM_FIGHTINIUM_Z 389
#define ITEM_POISONIUM_Z 390
#define ITEM_GROUNDIUM_Z 391
#define ITEM_FLYINIUM_Z 392
#define ITEM_PSYCHIUM_Z 393
#define ITEM_BUGINIUM_Z 394
#define ITEM_ROCKIUM_Z 395
#define ITEM_GHOSTIUM_Z 396
#define ITEM_DRAGONIUM_Z 397
#define ITEM_DARKINIUM_Z 398
#define ITEM_STEELIUM_Z 399
#define ITEM_FAIRIUM_Z 400
#define ITEM_PIKANIUM_Z 401
#define ITEM_EEVIUM_Z 402
#define ITEM_SNORLIUM_Z 403
#define ITEM_MEWNIUM_Z 404
#define ITEM_DECIDIUM_Z 405
#define ITEM_INCINIUM_Z 406
#define ITEM_PRIMARIUM_Z 407
#define ITEM_LYCANIUM_Z 408
#define ITEM_MIMIKIUM_Z 409
#define ITEM_KOMMONIUM_Z 410
#define ITEM_TAPUNIUM_Z 411
#define ITEM_SOLGANIUM_Z 412
#define ITEM_LUNALIUM_Z 413
#define ITEM_MARSHADIUM_Z 414
#define ITEM_ALORAICHIUM_Z 415
#define ITEM_PIKASHUNIUM_Z 416
#define ITEM_ULTRANECROZIUM_Z 417

// Species-specific Held Items
#define ITEM_LIGHT_BALL 418
#define ITEM_LEEK 419
#define ITEM_STICK ITEM_LEEK // Pre-Gen VIII name
#define ITEM_THICK_CLUB 420
#define ITEM_LUCKY_PUNCH 421
#define ITEM_METAL_POWDER 422
#define ITEM_QUICK_POWDER 423
#define ITEM_DEEP_SEA_SCALE 424
#define ITEM_DEEPSEASCALE ITEM_DEEP_SEA_SCALE // Pre-Gen VI name
#define ITEM_DEEP_SEA_TOOTH 425
#define ITEM_DEEPSEATOOTH ITEM_DEEP_SEA_TOOTH // Pre-Gen VI name
#define ITEM_SOUL_DEW 426
#define ITEM_ADAMANT_ORB 427
#define ITEM_LUSTROUS_ORB 428
#define ITEM_GRISEOUS_ORB 429

// Incenses
#define ITEM_SEA_INCENSE 430
#define ITEM_LAX_INCENSE 431
#define ITEM_ODD_INCENSE 432
#define ITEM_ROCK_INCENSE 433
#define ITEM_FULL_INCENSE 434
#define ITEM_WAVE_INCENSE 435
#define ITEM_ROSE_INCENSE 436
#define ITEM_LUCK_INCENSE 437
#define ITEM_PURE_INCENSE 438

// Contest Scarves
#define ITEM_RED_SCARF 439
#define ITEM_BLUE_SCARF 440
#define ITEM_PINK_SCARF 441
#define ITEM_GREEN_SCARF 442
#define ITEM_YELLOW_SCARF 443

// EV Gain Modifiers
#define ITEM_MACHO_BRACE 444
#define ITEM_POWER_WEIGHT 445
#define ITEM_POWER_BRACER 446
#define ITEM_POWER_BELT 447
#define ITEM_POWER_LENS 448
#define ITEM_POWER_BAND 449
#define ITEM_POWER_ANKLET 450
#define ITEM_POWER_RING 451
#define ITEM_POWER_HELMET 452

// Type-boosting Held Items
#define ITEM_SILK_SCARF 453
#define ITEM_CHARCOAL 454
#define ITEM_MYSTIC_WATER 455
#define ITEM_MAGNET 456
#define ITEM_MIRACLE_SEED 457
#define ITEM_NEVER_MELT_ICE 458
#define ITEM_NEVERMELTICE ITEM_NEVER_MELT_ICE // Pre-Gen VI name
#define ITEM_BLACK_BELT 459
#define ITEM_BLACKBELT ITEM_BLACK_BELT // Gen II name
#define ITEM_POISON_BARB 460
#define ITEM_SOFT_SAND 461
#define ITEM_SHARP_BEAK 462
#define ITEM_TWISTED_SPOON 463
#define ITEM_TWISTEDSPOON ITEM_TWISTED_SPOON // Pre-Gen VI name
#define ITEM_SILVER_POWDER 464
#define ITEM_SILVERPOWDER ITEM_SILVER_POWDER // Pre-Gen VI name
#define ITEM_HARD_STONE 465
#define ITEM_SPELL_TAG 466
#define ITEM_DRAGON_FANG 467
#define ITEM_BLACK_GLASSES 468
#define ITEM_BLACKGLASSES ITEM_BLACK_GLASSES // Pre-Gen VI name
#define ITEM_METAL_COAT 469

// Choice Items
#define ITEM_CHOICE_BAND 470
#define ITEM_CHOICE_SPECS 471
#define ITEM_CHOICE_SCARF 472

// Status Orbs
#define ITEM_FLAME_ORB 473
#define ITEM_TOXIC_ORB 474

// Weather Rocks
#define ITEM_DAMP_ROCK 475
#define ITEM_HEAT_ROCK 476
#define ITEM_SMOOTH_ROCK 477
#define ITEM_ICY_ROCK 478

// Terrain Seeds
#define ITEM_ELECTRIC_SEED 479
#define ITEM_PSYCHIC_SEED 480
#define ITEM_MISTY_SEED 481
#define ITEM_GRASSY_SEED 482

// Type-activated Stat Modifiers
#define ITEM_ABSORB_BULB 483
#define ITEM_CELL_BATTERY 484
#define ITEM_LUMINOUS_MOSS 485
#define ITEM_SNOWBALL 486

// Misc. Held Items
#define ITEM_BRIGHT_POWDER 487
#define ITEM_BRIGHTPOWDER ITEM_BRIGHT_POWDER // Pre-Gen VI name
#define ITEM_WHITE_HERB 488
#define ITEM_EXP_SHARE 489
#define ITEM_EXP_ALL ITEM_EXP_SHARE // Gen I name
#define ITEM_QUICK_CLAW 490
#define ITEM_SOOTHE_BELL 491
#define ITEM_MENTAL_HERB 492
#define ITEM_KINGS_ROCK 493
#define ITEM_AMULET_COIN 494
#define ITEM_CLEANSE_TAG 495
#define ITEM_SMOKE_BALL 496
#define ITEM_FOCUS_BAND 497
#define ITEM_LUCKY_EGG 498
#define ITEM_SCOPE_LENS 499
#define ITEM_LEFTOVERS 500
#define ITEM_SHELL_BELL 501
#define ITEM_WIDE_LENS 502
#define ITEM_MUSCLE_BAND 503
#define ITEM_WISE_GLASSES 504
#define ITEM_EXPERT_BELT 505
#define ITEM_LIGHT_CLAY 506
#define ITEM_LIFE_ORB 507
#define ITEM_POWER_HERB 508
#define ITEM_FOCUS_SASH 509
#define ITEM_ZOOM_LENS 510
#define ITEM_METRONOME 511
#define ITEM_IRON_BALL 512
#define ITEM_LAGGING_TAIL 513
#define ITEM_DESTINY_KNOT 514
#define ITEM_BLACK_SLUDGE 515
#define ITEM_GRIP_CLAW 516
#define ITEM_STICKY_BARB 517
#define ITEM_SHED_SHELL 518
#define ITEM_BIG_ROOT 519
#define ITEM_RAZOR_CLAW 520
#define ITEM_RAZOR_FANG 521
#define ITEM_EVIOLITE 522
#define ITEM_FLOAT_STONE 523
#define ITEM_ROCKY_HELMET 524
#define ITEM_AIR_BALLOON 525
#define ITEM_RED_CARD 526
#define ITEM_RING_TARGET 527
#define ITEM_BINDING_BAND 528
#define ITEM_EJECT_BUTTON 529
#define ITEM_WEAKNESS_POLICY 530
#define ITEM_ASSAULT_VEST 531
#define ITEM_SAFETY_GOGGLES 532
#define ITEM_ADRENALINE_ORB 533
#define ITEM_TERRAIN_EXTENDER 534
#define ITEM_PROTECTIVE_PADS 535
#define ITEM_THROAT_SPRAY 536
#define ITEM_EJECT_PACK 537
#define ITEM_HEAVY_DUTY_BOOTS 538
#define ITEM_BLUNDER_POLICY 539
#define ITEM_ROOM_SERVICE 540
#define ITEM_UTILITY_UMBRELLA 541

// Berries
#if B_CONFUSE_BERRIES_HEAL >= GEN_8
    #define CONFUSE_BERRY_HEAL_FRACTION 3
#elif B_CONFUSE_BERRIES_HEAL == GEN_7
    #define CONFUSE_BERRY_HEAL_FRACTION 2
#else
    #define CONFUSE_BERRY_HEAL_FRACTION 8
#endif

#define CONFUSE_BERRY_HP_FRACTION ((B_CONFUSE_BERRIES_HEAL >= GEN_7) ? 4 : 2)

#define ITEM_CHERI_BERRY 542
#define ITEM_CHESTO_BERRY 543
#define ITEM_PECHA_BERRY 544
#define ITEM_RAWST_BERRY 545
#define ITEM_ASPEAR_BERRY 546
#define ITEM_LEPPA_BERRY 547
#define ITEM_ORAN_BERRY 548
#define ITEM_PERSIM_BERRY 549
#define ITEM_LUM_BERRY 550
#define ITEM_SITRUS_BERRY 551
#define ITEM_FIGY_BERRY 552
#define ITEM_WIKI_BERRY 553
#define ITEM_MAGO_BERRY 554
#define ITEM_AGUAV_BERRY 555
#define ITEM_IAPAPA_BERRY 556
#define ITEM_RAZZ_BERRY 557
#define ITEM_BLUK_BERRY 558
#define ITEM_NANAB_BERRY 559
#define ITEM_WEPEAR_BERRY 560
#define ITEM_PINAP_BERRY 561
#define ITEM_POMEG_BERRY 562
#define ITEM_KELPSY_BERRY 563
#define ITEM_QUALOT_BERRY 564
#define ITEM_HONDEW_BERRY 565
#define ITEM_GREPA_BERRY 566
#define ITEM_TAMATO_BERRY 567
#define ITEM_CORNN_BERRY 568
#define ITEM_MAGOST_BERRY 569
#define ITEM_RABUTA_BERRY 570
#define ITEM_NOMEL_BERRY 571
#define ITEM_SPELON_BERRY 572
#define ITEM_PAMTRE_BERRY 573
#define ITEM_WATMEL_BERRY 574
#define ITEM_DURIN_BERRY 575
#define ITEM_BELUE_BERRY 576
#define ITEM_CHILAN_BERRY 577
#define ITEM_OCCA_BERRY 578
#define ITEM_PASSHO_BERRY 579
#define ITEM_WACAN_BERRY 580
#define ITEM_RINDO_BERRY 581
#define ITEM_YACHE_BERRY 582
#define ITEM_CHOPLE_BERRY 583
#define ITEM_KEBIA_BERRY 584
#define ITEM_SHUCA_BERRY 585
#define ITEM_COBA_BERRY 586
#define ITEM_PAYAPA_BERRY 587
#define ITEM_TANGA_BERRY 588
#define ITEM_CHARTI_BERRY 589
#define ITEM_KASIB_BERRY 590
#define ITEM_HABAN_BERRY 591
#define ITEM_COLBUR_BERRY 592
#define ITEM_BABIRI_BERRY 593
#define ITEM_ROSELI_BERRY 594
#define ITEM_LIECHI_BERRY 595
#define ITEM_GANLON_BERRY 596
#define ITEM_SALAC_BERRY 597
#define ITEM_PETAYA_BERRY 598
#define ITEM_APICOT_BERRY 599
#define ITEM_LANSAT_BERRY 600
#define ITEM_STARF_BERRY 601
#define ITEM_ENIGMA_BERRY 602
#define ITEM_MICLE_BERRY 603
#define ITEM_CUSTAP_BERRY 604
#define ITEM_JABOCA_BERRY 605
#define ITEM_ROWAP_BERRY 606
#define ITEM_KEE_BERRY 607
#define ITEM_MARANGA_BERRY 608
#define ITEM_ENIGMA_BERRY_E_READER 609

#define FIRST_BERRY_INDEX ITEM_CHERI_BERRY
#define LAST_BERRY_INDEX  ITEM_ENIGMA_BERRY_E_READER

// TMs/HMs
#define ITEM_TR01 610
#define ITEM_TR02 611
#define ITEM_TR03 612
#define ITEM_TR04 613
#define ITEM_TR05 614
#define ITEM_TR06 615
#define ITEM_TR07 616
#define ITEM_TR08 617
#define ITEM_TR09 618
#define ITEM_TR10 619
#define ITEM_TR11 620
#define ITEM_TR12 621
#define ITEM_TR13 622
#define ITEM_TR14 623
#define ITEM_TR15 624
#define ITEM_TR16 625
#define ITEM_TR17 626
#define ITEM_TR18 627
#define ITEM_TR19 628
#define ITEM_TR20 629
#define ITEM_TR21 630
#define ITEM_TR22 631
#define ITEM_TR23 632
#define ITEM_TR24 633
#define ITEM_TR25 634
#define ITEM_TR26 635
#define ITEM_TR27 636
#define ITEM_TR28 637
#define ITEM_TR29 638
#define ITEM_TR30 639
#define ITEM_TR31 640
#define ITEM_TR32 641
#define ITEM_TR33 642
#define ITEM_TR34 643
#define ITEM_TR35 644
#define ITEM_TR36 645
#define ITEM_TR37 646
#define ITEM_TR38 647
#define ITEM_TR39 648
#define ITEM_TR40 649
#define ITEM_TR41 650
#define ITEM_TR42 651
#define ITEM_TR43 652
#define ITEM_TR44 653
#define ITEM_TR45 654
#define ITEM_TR46 655
#define ITEM_TR47 656
#define ITEM_TR48 657
#define ITEM_TR49 658
#define ITEM_TR50 659
#define ITEM_TR51 660
#define ITEM_TR52 661
#define ITEM_TR53 662
#define ITEM_TR54 663
#define ITEM_TR55 664
#define ITEM_TR56 665
#define ITEM_TR57 666
#define ITEM_TR58 667
#define ITEM_TR59 668
#define ITEM_TR60 669
#define ITEM_TR61 670
#define ITEM_TR62 671
#define ITEM_TR63 672
#define ITEM_TR64 673
#define ITEM_TR65 674
#define ITEM_TR66 675
#define ITEM_TR67 676
#define ITEM_TR68 677
#define ITEM_TR69 678
#define ITEM_TR70 679
#define ITEM_TR71 680
#define ITEM_TR72 681
#define ITEM_TR73 682
#define ITEM_TR74 683
#define ITEM_TR75 684
#define ITEM_TR76 685
#define ITEM_TR77 686
#define ITEM_TR78 687
#define ITEM_TR79 688
#define ITEM_TR80 689
#define ITEM_TR81 690
#define ITEM_TR82 691
#define ITEM_TR83 692
#define ITEM_TR84 693
#define ITEM_TR85 694
#define ITEM_TR86 695
#define ITEM_TR87 696
#define ITEM_TR88 697
#define ITEM_TR89 698
#define ITEM_TR90 699
#define ITEM_TR91 700
#define ITEM_TR92 701
#define ITEM_TR93 702
#define ITEM_TR94 703
#define ITEM_TR95 704
#define ITEM_TR96 705
#define ITEM_TR97 706
#define ITEM_TR98 707
#define ITEM_TR99 708
#define ITEM_TR100 709

#define ITEM_TM01 710
#define ITEM_TM02 711
#define ITEM_TM03 712
#define ITEM_TM04 713
#define ITEM_TM05 714
#define ITEM_TM06 715
#define ITEM_TM07 716
#define ITEM_TM08 717
#define ITEM_TM09 718
#define ITEM_TM10 719
#define ITEM_TM11 720
#define ITEM_TM12 721
#define ITEM_TM13 722
#define ITEM_TM14 723
#define ITEM_TM15 724
#define ITEM_TM16 725
#define ITEM_TM17 726
#define ITEM_TM18 727
#define ITEM_TM19 728
#define ITEM_TM20 729
#define ITEM_TM21 730
#define ITEM_TM22 731
#define ITEM_TM23 732
#define ITEM_TM24 733
#define ITEM_TM25 734
#define ITEM_TM26 735
#define ITEM_TM27 736
#define ITEM_TM28 737
#define ITEM_TM29 738
#define ITEM_TM30 739
#define ITEM_TM31 740
#define ITEM_TM32 741
#define ITEM_TM33 742
#define ITEM_TM34 743
#define ITEM_TM35 744
#define ITEM_TM36 745
#define ITEM_TM37 746
#define ITEM_TM38 747
#define ITEM_TM39 748
#define ITEM_TM40 749
#define ITEM_TM41 750
#define ITEM_TM42 751
#define ITEM_TM43 752
#define ITEM_TM44 753
#define ITEM_TM45 754
#define ITEM_TM46 755
#define ITEM_TM47 756
#define ITEM_TM48 757
#define ITEM_TM49 758
#define ITEM_TM50 759

#define ITEM_HM01 760
#define ITEM_HM02 761
#define ITEM_HM03 762
#define ITEM_HM04 763
#define ITEM_HM05 764
#define ITEM_HM06 765
#define ITEM_HM07 766
#define ITEM_HM08 767

// Charms
#define ITEM_OVAL_CHARM 768
#define ITEM_SHINY_CHARM 769
#define ITEM_CATCHING_CHARM 770
#define ITEM_EXP_CHARM 771

// Form-changing Key Items
#define ITEM_ROTOM_CATALOG 772
#define ITEM_GRACIDEA 773
#define ITEM_REVEAL_GLASS 774
#define ITEM_DNA_SPLICERS 775
#define ITEM_ZYGARDE_CUBE 776
#define ITEM_PRISON_BOTTLE 777
#define ITEM_N_SOLARIZER 778
#define ITEM_N_LUNARIZER 779
#define ITEM_REINS_OF_UNITY 780

// Battle Mechanic Key Items
#define ITEM_MEGA_RING 781
#define ITEM_Z_POWER_RING 782
#define ITEM_DYNAMAX_BAND 783

// Misc. Key Items
#define ITEM_BICYCLE 784
#define ITEM_MACH_BIKE 785
#define ITEM_ACRO_BIKE 786
#define ITEM_OLD_ROD 787
#define ITEM_GOOD_ROD 788
#define ITEM_SUPER_ROD 789
#define ITEM_DOWSING_MACHINE 790
#define ITEM_ITEMFINDER ITEM_DOWSING_MACHINE // Pre-Gen IV name
#define ITEM_DOWSING_MCHN ITEM_DOWSING_MACHINE // Gen IV-V name
#define ITEM_TOWN_MAP 791
#define ITEM_VS_SEEKER 792
#define ITEM_TM_CASE 793
#define ITEM_BERRY_POUCH 794
#define ITEM_POKEMON_BOX_LINK 795
#define ITEM_POKEMON_BOX ITEM_POKEMON_BOX_LINK // Pre-Gen VIII name
#define ITEM_COIN_CASE 796
#define ITEM_POWDER_JAR 797
#define ITEM_WAILMER_PAIL 798
#define ITEM_POKE_RADAR 799
#define ITEM_POKEBLOCK_CASE 800
#define ITEM_SOOT_SACK 801
#define ITEM_POKE_FLUTE 802
#define ITEM_FAME_CHECKER 803
#define ITEM_TEACHY_TV 804

// Story Key Items
#define ITEM_SS_TICKET 805
#define ITEM_EON_TICKET 806
#define ITEM_MYSTIC_TICKET 807
#define ITEM_AURORA_TICKET 808
#define ITEM_OLD_SEA_MAP 809
#define ITEM_LETTER 810
#define ITEM_DEVON_PARTS 811
#define ITEM_DEVON_GOODS ITEM_DEVON_PARTS // Pre-Gen VI name
#define ITEM_GO_GOGGLES 812
#define ITEM_DEVON_SCOPE 813
#define ITEM_BASEMENT_KEY 814
#define ITEM_SCANNER 815
#define ITEM_STORAGE_KEY 816
#define ITEM_KEY_TO_ROOM_1 817
#define ITEM_RM_1_KEY ITEM_KEY_TO_ROOM_1 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_2 818
#define ITEM_RM_2_KEY ITEM_KEY_TO_ROOM_2 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_4 819
#define ITEM_RM_4_KEY ITEM_KEY_TO_ROOM_4 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_6 820
#define ITEM_RM_6_KEY ITEM_KEY_TO_ROOM_6 // Pre-Gen VI name
#define ITEM_METEORITE 821
#define ITEM_MAGMA_EMBLEM 822
#define ITEM_CONTEST_PASS 823
#define ITEM_PARCEL 824
#define ITEM_OAKS_PARCEL ITEM_PARCEL // Pre-Gen IV name
#define ITEM_SECRET_KEY 825
#define ITEM_BIKE_VOUCHER 826
#define ITEM_GOLD_TEETH 827
#define ITEM_CARD_KEY 828
#define ITEM_LIFT_KEY 829
#define ITEM_SILPH_SCOPE 830
#define ITEM_TRI_PASS 831
#define ITEM_RAINBOW_PASS 832
#define ITEM_TEA 833
#define ITEM_RUBY 834
#define ITEM_SAPPHIRE 835

// GEN IX ITEMS
#define ITEM_ABILITY_SHIELD 836
#define ITEM_CLEAR_AMULET 837
#define ITEM_PUNCHING_GLOVE 838
#define ITEM_COVERT_CLOAK 839
#define ITEM_LOADED_DICE 840
#define ITEM_AUSPICIOUS_ARMOR 841
#define ITEM_BOOSTER_ENERGY 842
#define ITEM_BIG_BAMBOO_SHOOT 843
#define ITEM_GIMMIGHOUL_COIN 844
#define ITEM_LEADERS_CREST 845
#define ITEM_MALICIOUS_ARMOR 846
#define ITEM_MIRROR_HERB 847
#define ITEM_SCROLL_OF_DARKNESS 848
#define ITEM_SCROLL_OF_WATERS 849
#define ITEM_TERA_ORB 850
#define ITEM_TINY_BAMBOO_SHOOT 851

#define ITEM_BUG_TERA_SHARD 852
#define ITEM_DARK_TERA_SHARD 853
#define ITEM_DRAGON_TERA_SHARD 854
#define ITEM_ELECTRIC_TERA_SHARD 855
#define ITEM_FAIRY_TERA_SHARD 856
#define ITEM_FIGHTING_TERA_SHARD 857
#define ITEM_FIRE_TERA_SHARD 858
#define ITEM_FLYING_TERA_SHARD 859
#define ITEM_GHOST_TERA_SHARD 860
#define ITEM_GRASS_TERA_SHARD 861
#define ITEM_GROUND_TERA_SHARD 862
#define ITEM_ICE_TERA_SHARD 863
#define ITEM_NORMAL_TERA_SHARD 864
#define ITEM_POISON_TERA_SHARD 865
#define ITEM_PSYCHIC_TERA_SHARD 866
#define ITEM_ROCK_TERA_SHARD 867
#define ITEM_STEEL_TERA_SHARD 868
#define ITEM_WATER_TERA_SHARD 869

#define ITEM_ADAMANT_CRYSTAL 870
#define ITEM_GRISEOUS_CORE 871
#define ITEM_LUSTROUS_GLOBE 872

#define ITEM_BLACK_AUGURITE 873
#define ITEM_LINKING_CORD 874
#define ITEM_PEAT_BLOCK 875
#define ITEM_BERSERK_GENE 876

#define ITEM_FAIRY_FEATHER 877
#define ITEM_SYRUPY_APPLE 878
#define ITEM_UNREMARKABLE_TEACUP 879
#define ITEM_MASTERPIECE_TEACUP 880
#define ITEM_CORNERSTONE_MASK 881
#define ITEM_WELLSPRING_MASK 882
#define ITEM_HEARTHFLAME_MASK 883
#define ITEM_HEALTH_MOCHI 884
#define ITEM_MUSCLE_MOCHI 885
#define ITEM_RESIST_MOCHI 886
#define ITEM_GENIUS_MOCHI 887
#define ITEM_CLEVER_MOCHI 888
#define ITEM_SWIFT_MOCHI 889
#define ITEM_ALERT_MOCHI 890
#define ITEM_KEEN_MOCHI 891
#define ITEM_FRESH_START_MOCHI 892
#define ITEM_GLIMMERING_CHARM 893
#define ITEM_METAL_ALLOY 894
#define ITEM_STELLAR_TERA_SHARD 895

#define ITEM_JUBILIFE_MUFFIN 896
#define ITEM_REMEDY 897
#define ITEM_FINE_REMEDY 898
#define ITEM_SUPERB_REMEDY 899
#define ITEM_AUX_EVASION 900
#define ITEM_AUX_GUARD 901
#define ITEM_AUX_POWER 902
#define ITEM_AUX_POWERGUARD 903
#define ITEM_CHOICE_DUMPLING 904
#define ITEM_SWAP_SNACK 905
#define ITEM_TWICE_SPICED_RADISH 906
#define ITEM_POKESHI_DOLL 907

#define ITEM_STRANGE_BALL 910

// HOPO BERRY
// LEGEND PLATE

#define ITEMS_COUNT 911
#define ITEM_FIELD_ARROW ITEMS_COUNT

// A special item id associated with "Cancel"/"Exit" etc. in a list of items or decorations
// Its icon is defined at ITEMS_COUNT as the "return to field" arrow
#define ITEM_LIST_END 0xFFFF

// Range of berries given out by various NPCS
#define FIRST_BERRY_MASTER_BERRY      ITEM_POMEG_BERRY
#define LAST_BERRY_MASTER_BERRY       ITEM_NOMEL_BERRY
#define FIRST_BERRY_MASTER_WIFE_BERRY ITEM_CHERI_BERRY
#define LAST_BERRY_MASTER_WIFE_BERRY  ITEM_SITRUS_BERRY
#define FIRST_KIRI_BERRY              ITEM_POMEG_BERRY
#define LAST_KIRI_BERRY               ITEM_NOMEL_BERRY
#define FIRST_ROUTE_114_MAN_BERRY     ITEM_RAZZ_BERRY
#define LAST_ROUTE_114_MAN_BERRY      ITEM_PINAP_BERRY

// Range of Nature Mints & Type Gems for Pickup
#define FIRST_NATURE_MINT			  ITEM_LONELY_MINT
#define LAST_NATURE_MINT			  ITEM_FOCUSED_MINT
#define RANDOM_NATURE_MINT			  1000
#define FIRST_TYPE_GEM			  	  ITEM_NORMAL_GEM
#define LAST_TYPE_GEM			 	  ITEM_FAIRY_GEM
#define RANDOM_TYPE_GEM 			  1001
#define FIRST_STAT_FEATHER		  	  ITEM_HEALTH_FEATHER
#define LAST_STAT_FEATHER		 	  ITEM_KEEN_FEATHER
#define RANDOM_STAT_FEATHER 		  1002


#define NUM_BERRY_MASTER_BERRIES          (LAST_BERRY_MASTER_BERRY - FIRST_BERRY_MASTER_BERRY + 1)
#define NUM_BERRY_MASTER_BERRIES_SKIPPED  (FIRST_BERRY_MASTER_BERRY - FIRST_BERRY_INDEX)
#define NUM_BERRY_MASTER_WIFE_BERRIES     (LAST_BERRY_MASTER_WIFE_BERRY - FIRST_BERRY_MASTER_WIFE_BERRY + 1)
#define NUM_KIRI_BERRIES                  (LAST_KIRI_BERRY - FIRST_KIRI_BERRY + 1)
#define NUM_KIRI_BERRIES_SKIPPED          (FIRST_KIRI_BERRY - FIRST_BERRY_INDEX)
#define NUM_ROUTE_114_MAN_BERRIES         (LAST_ROUTE_114_MAN_BERRY - FIRST_ROUTE_114_MAN_BERRY + 1)
#define NUM_ROUTE_114_MAN_BERRIES_SKIPPED (FIRST_ROUTE_114_MAN_BERRY - FIRST_BERRY_INDEX)
#define NUM_NATURE_MINTS                  (LAST_NATURE_MINT - FIRST_NATURE_MINT + 1)
#define NUM_TYPE_GEM 	                  (LAST_TYPE_GEM - FIRST_TYPE_GEM + 1)
#define NUM_STAT_FEATHER                  (LAST_STAT_FEATHER - FIRST_STAT_FEATHER + 1)

#define ITEM_TO_BERRY(itemId) (((itemId) - FIRST_BERRY_INDEX) + 1)
#define ITEM_TO_MAIL(itemId) ((itemId) - FIRST_MAIL_INDEX)
#define MAIL_NONE 0xFF
#define ITEM_TO_MULCH(itemId)(((itemId) - ITEM_GROWTH_MULCH) + 1)

#define NUM_TECHNICAL_RECORDS 100
#define NUM_TECHNICAL_MACHINES 50
#define NUM_HIDDEN_MACHINES 8

#define MAX_BAG_ITEM_CAPACITY         999
#define MAX_PC_ITEM_CAPACITY          999
#define MAX_PYRAMID_BAG_ITEM_CAPACITY  99 // Values higher than 255 require free SaveBlock2 space.

#define MAX_ITEM_DIGITS         ((MAX_BAG_ITEM_CAPACITY > 99) ? 3 : 2)
#define MAX_PYRAMID_ITEM_DIGITS ((MAX_PYRAMID_BAG_ITEM_CAPACITY > 99) ? 3 : 2)

// Secondary IDs for rods
#define OLD_ROD   0
#define GOOD_ROD  1
#define SUPER_ROD 2

// Secondary IDs for bikes
#define MACH_BIKE 0
#define ACRO_BIKE 1

// Item parameters for EXP Candies
#define EXP_100   1
#define EXP_800   2
#define EXP_3000  3
#define EXP_10000 4
#define EXP_30000 5

// Item type IDs (used to determine the exit callback)
#define ITEM_USE_MAIL             0
#define ITEM_USE_PARTY_MENU       1
#define ITEM_USE_FIELD            2
#define ITEM_USE_PBLOCK_CASE      3
#define ITEM_USE_BAG_MENU         4 // No exit callback, stays in bag menu
#define ITEM_USE_PARTY_MENU_MOVES 5

// Item battle script IDs (need to be non-zero)
#define EFFECT_ITEM_RESTORE_HP              1
#define EFFECT_ITEM_CURE_STATUS             2
#define EFFECT_ITEM_HEAL_AND_CURE_STATUS    3
#define EFFECT_ITEM_INCREASE_STAT           4
#define EFFECT_ITEM_SET_MIST                5
#define EFFECT_ITEM_SET_FOCUS_ENERGY        6
#define EFFECT_ITEM_ESCAPE                  7
#define EFFECT_ITEM_THROW_BALL              8
#define EFFECT_ITEM_REVIVE                  9
#define EFFECT_ITEM_RESTORE_PP              10
#define EFFECT_ITEM_INCREASE_ALL_STATS      11
#define EFFECT_ITEM_USE_POKE_FLUTE          12

// Enigma Berry dummy constant
#define EFFECT_ITEM_ENIGMA_BERRY_EREADER    1

#endif  // GUARD_CONSTANTS_ITEMS_H
